/// Flutter icons Instagram_clone
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Instagram_clone
///      fonts:
///       - asset: fonts/Instagram_clone.ttf
///
/// 
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';


class Instagram_clone {
  Instagram_clone._();

  static const _kFontFam = 'Instagram_clone';

  static const IconData comment_alt = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData igtv = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData like = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData like2 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData more = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData photo = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData post = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData direct2 = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData give = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData direct = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData comment_empty = const IconData(0xf0e5, fontFamily: _kFontFam);
}
